#vim: set ft=conf:
$color0 = rgba(01091cff) #01091c
#vim: set ft=conf:
$color1 = rgba(283345ff) #283345
#vim: set ft=conf:
$color2 = rgba(141a2aff) #141a2a
#vim: set ft=conf:
$color3 = rgba(555764ff) #555764
#vim: set ft=conf:
$color4 = rgba(3b1d1fff) #3b1d1f
#vim: set ft=conf:
$color5 = rgba(5b2934ff) #5b2934
#vim: set ft=conf:
$color6 = rgba(9a4854ff) #9a4854
#vim: set ft=conf:
$color7 = rgba(bcb2baff) #bcb2ba
#vim: set ft=conf:
$color8 = rgba(8f2a32ff) #8f2a32
#vim: set ft=conf:
$color9 = rgba(b07e7fff) #b07e7f
#vim: set ft=conf:
$color10 = rgba(1b0002ff) #1b0002
#vim: set ft=conf:
$color11 = rgba(bb4f5eff) #bb4f5e
#vim: set ft=conf:
$color12 = rgba(753c4bff) #753c4b
#vim: set ft=conf:
$color13 = rgba(68121dff) #68121d
#vim: set ft=conf:
$color14 = rgba(9c6a75ff) #9c6a75
#vim: set ft=conf:
$color15 = rgba(3b4453ff) #3b4453
