windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = workspace 6 silent, class:^(Slack)$
windowrulev2 = workspace 1 silent, title:^(GLava)$
windowrulev2 = workspace 4 silent, class:^(obsidian)$
windowrulev2 = workspace 4 silent, title:^(vimwiki-notes)$
windowrulev2 = workspace 10 silent,title:^(btop)$

windowrulev2 = workspace 5, class:^(Spotify)$
windowrulev2 = workspace 9, class:^(FreeTube)$
windowrulev2 = workspace 9, title:^(DDLC)$
windowrulev2 = workspace 3,class:^(Code)$
