workspace = 2,gapsin:0,gapsout:0
workspace = 3,gapsin:2,gapsout:0
workspace = 5,gapsin:0,gapsout:0,bordersize:0
workspace = 8,gapsin:0,gapsout:0
workspace = 9,gapsin:0,gapsout:0

workspace = 10, monitor:eDP-1
workspace = special:scratchpad, on-created-empty:foot
